### Placement description
version: '3.7'

services:
    nginx-proxy:
      image: 'jc21/nginx-proxy-manager:latest'
      restart: unless-stopped
      ports:
        - '80:80'
        - '81:81'
        - '443:443'
      volumes:
        - ./data:/data
        - ./letsencrypt:/etc/letsencrypt

    node_test_1:
      build: ./
      environment:
        NODE_ENV: "1"
      ports:
        - '4001:4001'

    node_test_2:
      build: ./
      environment:
        NODE_ENV: "2"
      ports:
        - '4002:4002'
